"""Add Twitter and Solana monitoring tables

Revision ID: a16d7ab72140
Revises: add_notification_system
Create Date: 2025-08-20 16:10:25.717763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a16d7ab72140'
down_revision: Union[str, Sequence[str], None] = 'add_notification_system'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solana_wallets',
    sa.Column('address', sa.String(length=44), nullable=False, comment='Solana钱包地址'),
    sa.Column('alias', sa.String(length=100), nullable=True, comment='钱包别名（用于显示）'),
    sa.Column('description', sa.Text(), nullable=True, comment='钱包描述信息'),
    sa.Column('min_amount_usd', sa.Numeric(precision=12, scale=2), nullable=False, comment='最小监控交易金额（USD）'),
    sa.Column('exclude_tokens', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='排除的代币列表（JSON格式）'),
    sa.Column('total_transactions', sa.Integer(), nullable=False, comment='总交易数量'),
    sa.Column('total_volume_usd', sa.Numeric(precision=15, scale=2), nullable=False, comment='总交易额（USD）'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用监控'),
    sa.Column('last_signature', sa.String(length=88), nullable=True, comment='最后检查的交易签名'),
    sa.Column('last_check_at', sa.String(length=50), nullable=True, comment='最后检查时间'),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='钱包标签（如: 聪明钱、巨鲸等）'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_solana_wallets_active_amount', 'solana_wallets', ['is_active', 'min_amount_usd'], unique=False)
    op.create_index(op.f('ix_solana_wallets_address'), 'solana_wallets', ['address'], unique=True)
    op.create_index(op.f('ix_solana_wallets_is_active'), 'solana_wallets', ['is_active'], unique=False)
    op.create_table('twitter_users',
    sa.Column('username', sa.String(length=100), nullable=False, comment='推特用户名（@后面的部分）'),
    sa.Column('display_name', sa.String(length=200), nullable=True, comment='推特显示名称'),
    sa.Column('twitter_id', sa.String(length=50), nullable=True, comment='推特用户ID'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用监控'),
    sa.Column('last_tweet_id', sa.String(length=50), nullable=True, comment='最后检查的推文ID'),
    sa.Column('last_check_at', sa.String(length=50), nullable=True, comment='最后检查时间'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_twitter_users_active', 'twitter_users', ['is_active'], unique=False)
    op.create_index(op.f('ix_twitter_users_is_active'), 'twitter_users', ['is_active'], unique=False)
    op.create_index(op.f('ix_twitter_users_twitter_id'), 'twitter_users', ['twitter_id'], unique=True)
    op.create_index(op.f('ix_twitter_users_username'), 'twitter_users', ['username'], unique=True)
    op.create_table('solana_transactions',
    sa.Column('signature', sa.String(length=88), nullable=False, comment='交易签名'),
    sa.Column('wallet_id', sa.Integer(), nullable=False, comment='关联的钱包ID'),
    sa.Column('transaction_type', sa.String(length=50), nullable=False, comment='交易类型：buy, sell, transfer, swap等'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='交易状态：confirmed, failed, pending'),
    sa.Column('token_address', sa.String(length=44), nullable=True, comment='代币合约地址'),
    sa.Column('token_symbol', sa.String(length=20), nullable=True, comment='代币符号'),
    sa.Column('token_name', sa.String(length=100), nullable=True, comment='代币名称'),
    sa.Column('token_decimals', sa.Integer(), nullable=True, comment='代币精度'),
    sa.Column('amount', sa.Numeric(precision=30, scale=18), nullable=True, comment='代币数量（原始精度）'),
    sa.Column('amount_usd', sa.Numeric(precision=15, scale=2), nullable=True, comment='交易金额（USD）'),
    sa.Column('fee', sa.Numeric(precision=15, scale=9), nullable=True, comment='交易手续费（SOL）'),
    sa.Column('fee_usd', sa.Numeric(precision=10, scale=2), nullable=True, comment='手续费（USD）'),
    sa.Column('token_price_usd', sa.Numeric(precision=15, scale=8), nullable=True, comment='代币价格（USD）'),
    sa.Column('sol_price_usd', sa.Numeric(precision=10, scale=2), nullable=True, comment='SOL价格（USD）'),
    sa.Column('counterpart_address', sa.String(length=44), nullable=True, comment='交易对手地址'),
    sa.Column('dex_name', sa.String(length=50), nullable=True, comment='DEX名称：Raydium, Orca, Jupiter等'),
    sa.Column('pool_address', sa.String(length=44), nullable=True, comment='流动性池地址'),
    sa.Column('slot', sa.String(length=20), nullable=True, comment='区块槽位'),
    sa.Column('block_time', sa.DateTime(timezone=True), nullable=True, comment='区块时间'),
    sa.Column('is_processed', sa.Boolean(), nullable=False, comment='是否已处理'),
    sa.Column('is_notified', sa.Boolean(), nullable=False, comment='是否已通知'),
    sa.Column('raw_transaction', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='原始交易数据（JSON格式）'),
    sa.Column('parsed_instructions', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='解析后的指令数据（JSON格式）'),
    sa.Column('solscan_url', sa.String(length=500), nullable=True, comment='Solscan浏览器链接'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['wallet_id'], ['solana_wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_solana_transactions_amount_time', 'solana_transactions', ['amount_usd', sa.literal_column('block_time DESC')], unique=False)
    op.create_index('idx_solana_transactions_token_time', 'solana_transactions', ['token_address', 'block_time'], unique=False)
    op.create_index('idx_solana_transactions_type_amount', 'solana_transactions', ['transaction_type', 'amount_usd'], unique=False)
    op.create_index('idx_solana_transactions_wallet_processed', 'solana_transactions', ['wallet_id', 'is_processed'], unique=False)
    op.create_index(op.f('ix_solana_transactions_block_time'), 'solana_transactions', ['block_time'], unique=False)
    op.create_index(op.f('ix_solana_transactions_is_notified'), 'solana_transactions', ['is_notified'], unique=False)
    op.create_index(op.f('ix_solana_transactions_is_processed'), 'solana_transactions', ['is_processed'], unique=False)
    op.create_index(op.f('ix_solana_transactions_signature'), 'solana_transactions', ['signature'], unique=True)
    op.create_index(op.f('ix_solana_transactions_token_address'), 'solana_transactions', ['token_address'], unique=False)
    op.create_index(op.f('ix_solana_transactions_transaction_type'), 'solana_transactions', ['transaction_type'], unique=False)
    op.create_index(op.f('ix_solana_transactions_wallet_id'), 'solana_transactions', ['wallet_id'], unique=False)
    op.create_table('tweets',
    sa.Column('tweet_id', sa.String(length=50), nullable=False, comment='推特推文ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='关联的推特用户ID'),
    sa.Column('content', sa.Text(), nullable=False, comment='推文完整内容'),
    sa.Column('tweet_url', sa.String(length=500), nullable=True, comment='推文链接'),
    sa.Column('ca_addresses', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='检测到的CA地址列表（JSON格式）'),
    sa.Column('is_processed', sa.Boolean(), nullable=False, comment='是否已处理'),
    sa.Column('is_notified', sa.Boolean(), nullable=False, comment='是否已通知'),
    sa.Column('like_count', sa.Integer(), nullable=False, comment='点赞数'),
    sa.Column('retweet_count', sa.Integer(), nullable=False, comment='转发数'),
    sa.Column('reply_count', sa.Integer(), nullable=False, comment='回复数'),
    sa.Column('tweet_created_at', sa.String(length=50), nullable=True, comment='推文发布时间'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['twitter_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # Skip JSON index for now - can be added later if needed
    op.create_index('idx_tweets_user_processed', 'tweets', ['user_id', 'is_processed'], unique=False)
    op.create_index(op.f('ix_tweets_is_notified'), 'tweets', ['is_notified'], unique=False)
    op.create_index(op.f('ix_tweets_is_processed'), 'tweets', ['is_processed'], unique=False)
    op.create_index(op.f('ix_tweets_tweet_id'), 'tweets', ['tweet_id'], unique=True)
    op.create_index(op.f('ix_tweets_user_id'), 'tweets', ['user_id'], unique=False)
    op.drop_index(op.f('ix_notification_templates_name'), table_name='notification_templates')
    op.create_unique_constraint(None, 'notification_templates', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notification_templates', type_='unique')
    op.create_index(op.f('ix_notification_templates_name'), 'notification_templates', ['name'], unique=True)
    op.drop_index(op.f('ix_tweets_user_id'), table_name='tweets')
    op.drop_index(op.f('ix_tweets_tweet_id'), table_name='tweets')
    op.drop_index(op.f('ix_tweets_is_processed'), table_name='tweets')
    op.drop_index(op.f('ix_tweets_is_notified'), table_name='tweets')
    op.drop_index('idx_tweets_user_processed', table_name='tweets')
    # No JSON index to drop
    op.drop_table('tweets')
    op.drop_index(op.f('ix_solana_transactions_wallet_id'), table_name='solana_transactions')
    op.drop_index(op.f('ix_solana_transactions_transaction_type'), table_name='solana_transactions')
    op.drop_index(op.f('ix_solana_transactions_token_address'), table_name='solana_transactions')
    op.drop_index(op.f('ix_solana_transactions_signature'), table_name='solana_transactions')
    op.drop_index(op.f('ix_solana_transactions_is_processed'), table_name='solana_transactions')
    op.drop_index(op.f('ix_solana_transactions_is_notified'), table_name='solana_transactions')
    op.drop_index(op.f('ix_solana_transactions_block_time'), table_name='solana_transactions')
    op.drop_index('idx_solana_transactions_wallet_processed', table_name='solana_transactions')
    op.drop_index('idx_solana_transactions_type_amount', table_name='solana_transactions')
    op.drop_index('idx_solana_transactions_token_time', table_name='solana_transactions')
    op.drop_index('idx_solana_transactions_amount_time', table_name='solana_transactions')
    op.drop_table('solana_transactions')
    op.drop_index(op.f('ix_twitter_users_username'), table_name='twitter_users')
    op.drop_index(op.f('ix_twitter_users_twitter_id'), table_name='twitter_users')
    op.drop_index(op.f('ix_twitter_users_is_active'), table_name='twitter_users')
    op.drop_index('idx_twitter_users_active', table_name='twitter_users')
    op.drop_table('twitter_users')
    op.drop_index(op.f('ix_solana_wallets_is_active'), table_name='solana_wallets')
    op.drop_index(op.f('ix_solana_wallets_address'), table_name='solana_wallets')
    op.drop_index('idx_solana_wallets_active_amount', table_name='solana_wallets')
    op.drop_table('solana_wallets')
    # ### end Alembic commands ###
